//! FFI facade for the Krystallos kernel.
//!
//! This is the only surface the Android side will ever see. In its final form
//! it is generated by UniFFI and exposes `Kernel` / `Session` / `RemoteFile`
//! objects; the control plane is `suspend fun` and the data plane is a
//! synchronous `readInto` over a direct `ByteBuffer`, because UniFFI's
//! zero-copy `&[u8]` support cannot be used from an async function and UniFFI
//! has no first-class stream type.
//!
//! # Why it exists this early
//!
//! Right now it holds a single probe. It is here from milestone M1 rather than
//! M7 because a static library is not the artifact that ships — a real `.so`
//! is, and the way a `.so` is laid out is not something to discover at the end.
//! Concretely, the build has to prove that:
//!
//! - libsmb2 links into a shared object rather than being dropped or left as an
//!   unresolved symbol,
//! - the result loads under Android's linker, which is stricter than the host
//!   one,
//! - and its loadable segments are 16 KB aligned. Google Play requires that for
//!   apps targeting Android 15+, and getting it wrong is not a build error — it
//!   is a `GNU_RELRO` segment that segfaults at startup on a 16 KB-page device.
//!
//! Checking all of that needs the real artifact, so the crate is born with one.

#![deny(unsafe_op_in_unsafe_fn)]
// MSVC's linker narrates what it is doing ("creating library ... and object
// ...") on stdout, and rustc surfaces that as a `linker_messages` warning on
// every cdylib link. It is toolchain chatter, not a problem with this crate,
// and it would otherwise be the only warning in a clean `cargo build`.
#![allow(linker_messages)]

/// Report whether the kernel's SMB backend is present and usable.
///
/// Returns `0` on success and `-1` on failure. Exists so the packaging path can
/// be exercised end to end — if libsmb2 were ever silently dropped from the
/// link, this returns `-1` instead of the `.so` merely being smaller.
///
/// # Safety
///
/// Safe to call from any thread, any number of times. It takes no arguments and
/// returns no pointers.
#[unsafe(no_mangle)]
pub extern "C" fn krystallos_link_probe() -> i32 {
    if krystallos_sys_smb2::link_probe() { 0 } else { -1 }
}
